"""empty message

Revision ID: 806a9f570192
Revises: 872b67274b70
Create Date: 2025-08-13 17:12:32.783899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806a9f570192'
down_revision = '872b67274b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joined_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('joined_at')

    # ### end Alembic commands ###
