"""add file column in post models

Revision ID: 872b67274b70
Revises: c097aeda8527
Create Date: 2025-08-06 10:34:25.856940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872b67274b70'
down_revision = 'c097aeda8527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('file')

    # ### end Alembic commands ###
